{% set name = "VetoPerf" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcedb230ed82505127bc62b558728d2e1d3197a4504ea4c0696310e961ed34ac
  patches:
    # use rootcling from build env when cross-compiling
    - rootcling-cross.patch  # [build_platform != target_platform]

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.12.0
    - make  # [unix]
    - pkg-config  # [unix]
    - root_base  # [build_platform != target_platform]
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - omicron >=4.0.0
    - gwollum >=4.0.0
    - root_base
  run:
    - omicron >=4.0.0
    - gwollum >=4.0.0
    - root_base

test:
  requires:
    - pkg-config
  commands:
    # sanity check
    - vp-makeperf version
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} {{ name|lower }}

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: VetoPerf is a software analysis tool designed to measure the performance of time-domain vetoes for gravitational-wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rhyspoulton
